services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - llm-translator-network

  web:
    build: .
    command: ["poetry", "run", "python", "llm_translator/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - llm-translator-network

volumes:
  postgres_data:

networks:
  llm-translator-network: